### PR TITLE
Make sure CI is passing again

### PR DESCRIPTION
**Pull request by tadeboro**
The CI was failing because a lot of things moved around since the repo was set up.

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
LGTM

**Review by Akasurde — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
```
<•andersson007_> Andrew Klychkov 
does anyone have any ideas why the doc fragment can't be found https://github.com/ansible-collections/community.kubevirt/pull/23 ? It exists:)
10:33 AM <github-linkbot> 
https://github.com/ansible-collections/community.kubevirt/pull/23 | open, created 2021-09-01T08:09:14Z by Andersson007: Change dependency from community.kubernetes to kubernetes.core  
10:36 AM 
→ Nukien2 joined (~Nukien2@ool-ad022598.dyn.optonline.net)
10:40 AM <•gwmngilfen-work> @gwmngilfen:ansible.im 
Morning
10:41 AM 
⇐ eramirez quit (~eramirez@49.149.131.61) Read error: Connection reset by peer
10:42 AM <felixfontein> Felix Fontein 
andersson007_: zuul's third party check doesn't care about collection dependencies, so if that doc fragment comes from a dependency, it will fail
10:42 AM 
→ eramirez joined (~eramirez@49.149.131.61)
10:42 AM <felixfontein> Felix Fontein 
andersson007_: that's why the third party check always fails in c.g for stable-1 (when we still had dependencies)
10:42 AM 
⇐ eramirez quit (~eramirez@49.149.131.61) Read error: Connection reset by peer
10:43 AM <felixfontein> Felix Fontein 
I would really add proper CI to that collection (at least sanity tests), and not just zuul third party, since that one is really basic (and very slow for what it does)
```

**Comment by Andersson007** [comment]
@tadeboro you are a savior of the collection, thanks for fixing this! @Akasurde thanks for reviewing!

**Pull request merged**
